version: 2.0.{build}
image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN: 
    secure: Gi55/aHqrZs6SjL0DCGl9jVTQLapvcroI21SLtMZ/7npQIwzoRrx1zA+sP+0O7jj
before_build:
- appveyor-retry dotnet restore .\src -v Minimal
build_script:
- dotnet build .\src
after_test:
- cmd: >-
    C:\Users\appveyor\.nuget\packages\OpenCover\4.6.519\tools\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:" C:\Users\appveyor\.nuget\packages\nunit.consolerunner\3.7.0\tools\nunit3-console.exe" -targetargs:"/domain:single  src\stream-net-tests\bin\debug\stream-net-tests.dll" -output:coverage.xml
    C:\Users\appveyor\.nuget\packages\coveralls.io\1.4.1\tools\coveralls.net.exe --opencover coverage.xml
on_finish:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'
    $wc.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\TestResult.xml))