version: 2.0.{build}
image: Visual Studio 2017

environment:
  COVERALLS_REPO_TOKEN: 
    secure: Gi55/aHqrZs6SjL0DCGl9jVTQLapvcroI21SLtMZ/7npQIwzoRrx1zA+sP+0O7jj
before_build:
- appveyor-retry dotnet restore .\src -v Minimal
build_script:
- dotnet build .\src
after_test:
- cmd: >-
    nuget locals global-packages -list
